from reportlab.lib.pagesizes import A4
from reportlab.pdfgen import canvas
from reportlab.lib import colors
from datetime import datetime
import os


def generate_certificate(user, score, total):

    percentage = round((score / total) * 100, 2) if total > 0 else 0

    # Grade
    if percentage >= 90:
        grade = "A+"
        achievement = "Outstanding Performance"
    elif percentage >= 80:
        grade = "A"
        achievement = "Excellent Performance"
    elif percentage >= 70:
        grade = "B"
        achievement = "Very Good Performance"
    elif percentage >= 50:
        grade = "C"
        achievement = "Successful Completion"
    else:
        grade = "D"
        achievement = "Participation"

    file_name = f"{user}_certificate.pdf"
    file_path = os.path.join(os.getcwd(), file_name)

    c = canvas.Canvas(file_path, pagesize=A4)

    width, height = A4

    # =========================
    # PREMIUM GOLD BORDER
    # =========================
    c.setStrokeColor(colors.gold)
    c.setLineWidth(5)
    c.rect(25, 25, width - 50, height - 50)

    c.setLineWidth(2)
    c.rect(40, 40, width - 80, height - 80)

    # =========================
    # HEADER
    # =========================
    c.setFont("Helvetica-Bold", 22)
    c.drawCentredString(
        width / 2,
        780,
        "AI Powered Quiz Management System"
    )

    # =========================
    # TITLE
    # =========================
    c.setFont("Helvetica-Bold", 32)
    c.drawCentredString(width / 2, 710, "CERTIFICATE")

    c.setFont("Helvetica", 18)
    c.drawCentredString(width / 2, 680, "OF ACHIEVEMENT")

    # =========================
    # BODY
    # =========================
    c.setFont("Helvetica", 14)
    c.drawCentredString(
        width / 2,
        620,
        "This certificate is proudly presented to"
    )

    # =========================
    # STUDENT NAME
    # =========================
    c.setFont("Helvetica-Bold", 30)
    c.drawCentredString(width / 2, 570, user)

    # =========================
    # DESCRIPTION
    # =========================
    c.setFont("Helvetica", 14)
    c.drawCentredString(
        width / 2,
        525,
        "For successfully completing the AI-Powered Quiz Assessment"
    )

    # =========================
    # ACHIEVEMENT
    # =========================
    c.setFont("Helvetica-Bold", 18)
    c.drawCentredString(width / 2, 475, achievement)

    # =========================
    # RESULTS
    # =========================
    c.setFont("Helvetica", 15)
    c.drawCentredString(width / 2, 430, f"Score: {score}/{total}")
    c.drawCentredString(width / 2, 400, f"Percentage: {percentage}%")
    c.drawCentredString(width / 2, 370, f"Grade: {grade}")

    # =========================
    # DATE
    # =========================
    issue_date = datetime.now().strftime("%d-%m-%Y")
    c.setFont("Helvetica", 12)
    c.drawString(80, 180, f"Issue Date: {issue_date}")

    # =========================
    # CERTIFICATE ID
    # =========================
    cert_id = f"CERT-{datetime.now().strftime('%Y%m%d')}-{score}{total}"
    c.drawString(80, 155, f"Certificate ID: {cert_id}")

    # =========================
    # SIGNATURES
    # =========================
    c.line(90, 100, 230, 100)
    c.drawString(120, 80, "Instructor")

    c.line(360, 100, 500, 100)
    c.drawString(405, 80, "Director")

    # =========================
    # FOOTER
    # =========================
    c.setFont("Helvetica-Oblique", 10)
    c.drawCentredString(
        width / 2,
        50,
        "Generated by AI Powered Quiz Management System"
    )

    c.save()

    return file_path